SET PATH=C:\MinGW\bin;%PATH%

gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include python/binding/swig_wrap.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/compound-file.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/compound-file-difat.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/compound-file-directory.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/compound-file-fat.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/compound-file-header.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-arc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-circle.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-compress.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-color.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-ellipse.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-file.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-flag.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-format.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-hash.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-hoop.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-layer.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-line.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-logging.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-path.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-pattern.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-point.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-polygon.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-polyline.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-reader-writer.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-rect.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-satin-line.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-settings.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-spline.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-stitch.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-thread.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-time.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/emb-vector.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/hashtable.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/helpers-binary.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/helpers-misc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/thread-color.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-10o.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-100.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-art.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-bmc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-bro.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-cnd.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-col.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-csd.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-csv.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dat.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dem.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dsb.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dst.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dsz.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-dxf.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-edr.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-emd.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-exp.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-exy.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-eys.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-fxy.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-gc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-gnc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-gt.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-hus.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-inb.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-inf.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-jef.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-ksm.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-max.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-mit.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-new.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-ofm.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pcd.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pcm.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pcq.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pcs.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pec.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pel.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pem.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-pes.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-phb.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-phc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-plt.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-rgb.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-sew.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-shv.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-sst.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-stx.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-svg.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-t01.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-t09.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-tap.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-thr.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-txt.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-u00.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-u01.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-vip.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-vp3.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-xxx.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/format-zsk.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/geom-arc.c
gcc -c -I../libembroidery -Ipython/binding -I../../../Python/include ../libembroidery/geom-line.c
gcc -shared -o python/binding/_libembroidery.pyd *.o -L c:\Python\libs -lpython27
